[[BC_QOS]]
== Bandwidth-controller QoS Register Interface

Controllers, such as memory controllers, that support bandwidth allocation and
bandwidth usage monitoring provide a memory-mapped register programming
interface.

.Bandwidth-Controller QoS register layout
[width=100%]
[%header, cols="^3,10,^3, 18, 5"]
|===
|Offset|Name              |Size    |Description                 | Optional?
|0     |`bc_capabilities` |8       |<<BC_CAP, Capabilities>>    | No
|8     |`bc_mon_ctl`      |8       |<<BC_MCTL, Usage monitoring
                                      control>>                 | Yes
|16    |`bc_mon_ctr_val`  |8       |<<BC_MCTR, Monitoring
                                      counter value>>           | Yes
|24    |`bc_alloc_ctl`    |8       |<<BC_ALLOC, Bandwidth 
                                    allocation control>>        | Yes
|32    |`bc_bw_alloc`     |8       |<<BC_BMASK, Bandwidth 
                                    allocation>>                | Yes
|===

The reset value is 0 for the following registers fields.

* `bc_mon_ctl` - `BUSY` and `STATUS` fields
* `bc_alloc_ctl` - `BUSY` and `STATUS` fields

The reset value is `UNSPECIFIED` for all other registers and/or fields.

The bandwidth controllers at reset allocate all available bandwidth to `RCID`
value of 0. When the bandwidth controller supports bandwidth allocation per
access-type, `AT=0` of `RCID=0` is allocated all available bandwidth and all
other access-types associated with that `RCID` share the bandwidth allocation
with `AT=0`. The bandwidth allocation for all other `RCID` values is
`UNSPECIFIED`.

[[BC_CAP]]
=== Capabilities (`bc_capabilities`)

The `bc_capabilities` register is a read-only register that holds the
bandwidth-controller capabilities.

.Capabilities register fields
[wavedrom, , ]
....
{reg: [
  {bits:  8, name: 'VER'},
  {bits: 16, name: 'NBWBLKS'},
  {bits:  8, name: 'reserved'},
  {bits: 16, name: 'MRBWB'},
  {bits:  8, name: 'reserved'},
  {bits:  8, name: 'custom'},
], config:{lanes: 4, hspace:1024}}
....

The `VER` field holds the version of the specification implemented by the
bandwidth controller. The low nibble is used to hold the minor version of the
specification and the upper nibble is used to hold the major version of the
specification. For example, an implementation that supports version 1.0 of the
specification reports 0x10.

The `NBWBLKS` field holds the total number of available bandwidth blocks in 
the controller. The bandwidth represented by an available bandwidth block is
`UNSPECIFIED`. The bandwidth controller supports reserving bandwidth in
multiples of a bandwidth block and thereby support proportional allocation of
bandwidth.

Bandwidth controllers may limit the maximum bandwidth that may be reserved to
to be smaller than `NBWBLLKS`. The `MRBWB` field reports the maximum banwidth
blocks that may be reserved.

[NOTE]
====
The bandwidth controller needs to meter the bandwidth usage by a workload to
determine if it is exceeding its allocations and if required invoke necessary
measures to throttle the bandwidth usage by the workload. The instantaneous
bandwidth used by a workload may thus undershoot or overshoot the configured
allocation. The QoS capabilities are statistical in nature and are typically
designed to enforce the configured bandwidth over larger time windows. Not
allowing all available bandwidth blocks to be reserved for allocation may allow
the bandwidth controller to handle such transient inaccuracies.
====

[[BC_MCTL]]
=== Usage monitoring control (`bc_mon_ctl`)

The `bc_mon_ctl` register is used to control monitoring of bandwidth usage by a
`MCID`. When the controller does not support bandwidth usage monitoring the
`bc_mon_ctl` register is read-only zero.

.Usage monitoring control (`bc_mon_ctl`)
[wavedrom, , ]
....
{reg: [
  {bits:  5, name: 'OP (WARL)'},
  {bits:  3, name: 'AT (WARL)'},
  {bits: 12, name: 'MCID (WARL)'},
  {bits:  8, name: 'EVT_ID (WARL)'},
  {bits:  1, name: 'ATV (WARL)'},
  {bits:  3, name: 'WPRI'},
  {bits:  7, name: 'STATUS (RO)'},
  {bits:  1, name: 'BUSY (RO)'},
  {bits: 24, name: 'WPRI'},
], config:{lanes: 8, hspace:1024}}
....

Bandwidth controllers that support bandwidth usage monitoring implement a usage
monitoring counter for each supported `MCID`. The usage monitoring counter may
be configured to count a monitoring event. When an event matching the event
configured for the `MCID` occurs then the monitoring counter is updated. The
event matching may optionally be filtered by the access-type. The monitoring 
counter for bandwidth usage counts the number of bytes transferred by requests
matching the monitoring event as the requests go past the monitoring point.

The `OP` field is used to instruct the controller to perform an operation
listed in <<BC_MON_OP>>.

The `EVT_ID` field is used to program the identifier of the event to count in
the counter selected by `MCID`. The `AT` field is used to program the
access-type to count. 

When the `EVT_ID` for a `MCID` is selected as 0, the counter retains its
current value but stops counting.

When `EVT_ID` is programmed with a non-zero and legal value, the counter resets
to 0, the `OVF` bit is cleared to 0, and the counter starts counting the
programmed events for requests with `MCID` and `AT` (if `ATV` is 1). When `ATV`
is 0, the counter counts requests with all access-types and the `AT` value is
ignored.

A controller that does not support monitoring by access-type may hardwire the
`ATV` and `AT` fields to 0.

[[BC_MON_OP]]
.Usage monitoring operations (`OP`)
[width=100%]
[%header, cols="16,^12,70"]
|===
|Operation     | Encoding ^| Description
|--            | 0         | Reserved for future standard use.
|`CONFIG_EVENT`| 1         | Configure the counter selected by `MCID` to count
                             the event selected by `EVT_ID`, `AT`, and `ATV`.
                             The `EVT_ID` encodings are listed in <<BC_EVT_ID>>.
|`READ_COUNTER`| 2         | Snapshot the value of the counter selected by
                             `MCID` into `bc_mon_ctr_val` register. The
                             `EVT_ID`, `AT` and `ATV` fields are not used by
                             this operation.
| --           | 3-23      | Reserved for future standard use.
| --           | 24-31     | Designated for custom use.
|===


[[BC_EVT_ID]]
.Bandwidth monitoring event ID (`EVT_ID`)
[width=100%]
[%header, cols="15,^10,40"]
|===
|Event ID      | Encoding ^| Description
|`None`        | 0         | Counter does not count and retains its value.
|`Total Read
  and Write
  byte count`  | 1         | Counter is incremented by the number of bytes
                             transferred by a matching read or write request
                             as the requests go past the monitor.
|`Total Read
  byte count`  | 2         | Counter is incremented by the number of bytes
                             transferred by a matching read request as the
                             requests go past the monitor
|`Total Write
  byte count`  | 3         | Counter is incremented by the number of bytes
                             transferred by a matching write request as the
                             requests go past the monitor
| --           | 4-127     | Reserved for future standard use.
| --           | 128-256   | Designated for custom use.
|===

When the `bc_mon_ctl` is written, the controller may need to perform several
actions that may not complete synchronously with the write. A write to the
`bc_mon_ctl` sets the `BUSY` bit to 1 indicating the controller is performing
the requested operation. When the `BUSY` bit reads 0 the operation is complete
and the `STATUS` field provides a status value (<<BC_MON_STS>>) of the
requested operation.

[[BC_MON_STS]]
.`bc_mon_ctl.STATUS` field encodings
[width=100%]
[%header, cols="12,70"]
|===
|`STATUS` | Description
| 0       | Reserved
| 1       | Operation was successfully completed.
| 2       | Invalid operation (`OP`) requested.
| 3       | Operation requested for invalid `MCID`.
| 4       | Operation requested for invalid `EVT_ID`.
| 5       | Operation requested for invalid `AT`.
| 6-63    | Reserved for future standard use.
| 64-127  | Designated for custom use.
|===

Behavior of writes to the `bc_mon_ctl` when `BUSY` is 1 is `UNSPECIFIED`. Some
implementations may ignore the second write and others may perform the
operation determined by the second write. Software must verify that `BUSY` is 0
before writing `bc_mon_ctl`.

[[BC_MCTR]]
=== Monitoring counter value (`bc_mon_ctr_val`)

The `bc_mon_ctr_val` is a read-only register that holds a snapshot of the
counter requested by `READ_COUNTER` operation. When the controller does not
support bandwidth usage monitoring the `bc_mon_ctr_val` register is read-only
zero.

.Usage monitoring counter value (`bc_mon_ctr_val`)
[wavedrom, , ]
....
{reg: [
  {bits:  62, name: 'CTR'},
  {bits:  1, name: 'INVALID'},
  {bits:  1, name: 'OVF'},
], config:{lanes: 4, hspace:1024}}
....

The counter is valid if the `INVALID` field is 0. The counter may be marked
`INVALID` if the controller for `UNSPECIFIED` reasons determine the count to be
not valid. The counters marked `INVALID` may become valid in future. If an
unsigned integer overflow of the counter occurs then the `OVF` bit is set to 1.

[NOTE]
====
A counter may be marked as `INVALID` if the controller has not been able to 
establish an accurate counter value for the monitored event.
====

The counter provides the byte transferred by requests matching the `EVT_ID` as
the requests go past the monitoring point. A bandwidth value may be determined
by reading the byte count value at two instances of time `T1` and `T2`. If the
value of the counter at time `T1` was `B1` and at time `T2` is `B2` then the
bandwidth is as follows. The frequency of the time source is
latexmath:[T_{freq}].

[latexmath]
++++
    Bandwidth = T_{freq} \times \frac{ B2 - B1 }{T2 - T1}
++++

The width of the counter is `UNSPECIFIED`.

[NOTE]
====
The width of the counter is `UNSPECIFIED` but is recommended to be wide enough
to not cause more than one overflow per sample when sampled at a frequency of
1 Hz.

If an overflow was detected then software may discard that sample and reset the
counter and overflow indication by reprogramming the event using `CONFIG_EVENT`
operation.
====

[[BC_ALLOC]]
=== Bandwidth Allocation control (`bc_alloc_ctl`)

The `bc_alloc_ctl` register is used to control allocation of bandwidth to a
`RCID` per `AT`. If a controller does not support bandwidth allocation then the
register is read-only zero. If the controller does not support bandwidth
allocation per access-type then the `AT` field is read-only zero.

.Bandwidth allocation control (`bc_alloc_ctl`)
[wavedrom, , ]
....
{reg: [
  {bits:  5, name: 'OP (WARL)'},
  {bits:  3, name: 'AT (WARL)'},
  {bits: 12, name: 'RCID (WARL)'},
  {bits: 12, name: 'WPRI'},
  {bits:  7, name: 'STATUS (RO)'},
  {bits:  1, name: 'BUSY (RO)'},
  {bits: 24, name: 'WPRI'},
], config:{lanes: 8, hspace:1024}}
....

The `OP` field is used to instruct the bandwidth controller to perform an
operation listed in <<BC_ALLOC_OP>>. The `bc_alloc_ctl` register is used in
conjunction with the `bc_bw_alloc` register to perform bandwidth allocation
operations. When the requested operation uses the operands configured in
`bc_bw_alloc`, software must first program the `bc_bw_alloc` register with
the operands for the operation before requesting the operation.

[[BC_ALLOC_OP]]
.Bandwidth allocation operations (`OP`)
[width=100%]
[%header, cols="16,^12,70"]
|===
|Operation     | Encoding ^| Description
|--            | 0         | Reserved for future standard use.
|`CONFIG_LIMIT`| 1         | The `CONFIG_LIMIT` operation is used to establish
                             reserved bandwidth allocation for requests by
                             `RCID` and of access-type `AT`. The bandwidth
                             allocation is specified in `bc_bw_alloc` register.
|`READ_LIMIT`  | 2         | The `READ_LIMIT` operation is used to read back
                             the previously configured bandwidth allocation for
                             requests by `RCID` and of type `AT`. The current
                             configured allocation is written to `bc_bw_alloc`
                             register on completion of the operation.
| --           | 3-23      | Reserved for future standard use.
| --           | 24-31     | Designated for custom use.
|===

A bandwidth allocation must be configured for each supported access-type by 
the controller. When differentiated bandwidth allocation based on access-type
is not required, one of the access-types may be designated to hold a default
bandwidth allocation and the other access-types configured to share the
allocation with the default access-type. The behavior is `UNSPECIFIED` if
bandwidth is not allocated for each access-type supported by the controller.

When the `bc_alloc_ctl` is written, the controller may need to perform several
actions that may not complete synchronously with the write. A write to the
`bc_alloc_ctl` sets the `BUSY` bit to 1 indicating the controller is performing
the requested operation. When the `BUSY` bit reads 0 the operation is complete
and the `STATUS` field provides a status value (<<BC_ALLOC_STS>>) of the
requested operation.

[[BC_ALLOC_STS]]
.`bc_alloc_ctl.STATUS` field encodings
[width=100%]
[%header, cols="12,70"]
|===
|`STATUS` | Description
| 0       | Reserved
| 1       | Operation was successfully completed.
| 2       | Invalid operation (`OP`) requested.
| 3       | Operation requested for an invalid `RCID`.
| 4       | Operation requested for an invalid `AT`.
| 5       | Invalid/unsupported reserved bandwidth blocks requested.
| 6-63    | Reserved for future standard use.
| 64-127  | Designated for custom use.
|===

[[BC_BMASK]]
=== Bandwidth allocation (`bc_bw_alloc`)

The `bc_bw_alloc` is used to program reserved bandwidth blocks (`Rbwb`) for an
`RCID` for requests of access-type `AT` using the `CONFIG_LIMIT` operation. If a
controller does not support bandwidth allocation then the `bc_bw_alloc` register
is read-only zero.

The `bc_bw_alloc` holds the previously configured values for an `RCID` and `AT`
on successful completion of the `READ_LIMIT` operation.

The bandwidth is allocated in multiples of bandwidth blocks and the value in
`Rbwb` must be at least 1 and must not exceed `MRBWB` else the `CONFIG_LIMIT`
operation fails with `STATUS=5`. The sum of `Rbwb` allocated across all `RCID`
must not exceed `MRBWB` else the `CONFIG_LIMIT` operation fails with `STATUS=5`.

.Bandwidth allocation (`bc_bw_alloc`)
[wavedrom, , ]
....
{reg: [
  {bits: 16, name: 'Rbwb (WARL)'},
  {bits:  4, name: 'WPRI'},
  {bits:  8, name: 'Mweight (WARL)'},
  {bits:  3, name: 'sharedAT (WARL)'},
  {bits:  1, name: 'useShared (WARL)'},
  {bits: 32, name: 'WPRI'},
], config:{lanes: 8, hspace:1024}}
....

Bandwidth allocation is typically enforced by the bandwidth controller over
finite accounting windows. The process involves measuring the bandwidth
consumption over an accounting window and using the measured bandwidth to
determine if an `RCID` is exceeding its bandwidth allocations for each
access-types. The specifics of how the accounting window is implemented is
`UNSPECIFIED` but is expected to provide a statistically accurate control of 
the bandwidth usage over a few accounting intervals.

The `Rbwb` represents the bandwidth that is made available to a `RCID` for
requests matching `AT` even when all other `RCID` are using their full
allocation of bandwidth.

If there is non-reserved or unused bandwidth available in an accounting
interval then additional bandwidth may be made available to `RCID` that contend
for that bandwidth. The non-reserved or unused bandwidth is proportionately
shared by the contending RCIDs using the configured `Mweight`. The `Mweight`
parameter is a number between 0 and 255. A larger weight implies a greater
fraction of the bandwidth. A weight of 0 implies that the configured limit is a
hard limit and the use of unused or non-reserved bandwidth is not allowed.

The sharing of non-reserved bandwidth is not differentiated by access-type.
The `Mweight` parameter must be programmed identically for all access-types. If
this parameter is programmed differently for each access-type then the
controller may use the parameter configured for any of the access-types but the
behavior is otherwise well defined.

When the weight is not 0, the share of unused bandwidth made available to
`RCID=x` when it contents with another `RCID` that is also allowed to use unused
bandwidth is determined by the `Mweight` of `RCID=x` divided by the sum of
`Mweight` of all other contending `RCID`. This ratio `P` is as follows:

[latexmath]
++++
    P = \frac{Mweight_{x}}{\sum_{r=1}^{r=n} Mweight_{r}}
++++

[NOTE]
====
The bandwidth enforcement is typically work-conserving and allows unused
bandwidth to be used by requestors enabled to use unused bandwidth even if they
have consumed their `Rbwb`.

When contending for unused bandwidths the weighted share is typically 
computed among the `RCIDs` that are actively generating requests in that
accounting interval and have a non-zero weight programmed.
====

If unique bandwidth allocation is not required for an access-type then the
`useShared` may be set to 1 for `CONFIG_LIMIT` operation. When `useShared` is
set to 1, the `sharedAT` field specifies the access-type with which the
bandwidth allocation is shared by the access-type in `bc_alloc_ctl.AT`. When
`useShared` is 1, `Rbwb` and `Mweight` fields are ignored and the configurations
of access-type in `sharedAT` apply. If the access-type specified by `sharedAT`
does not have unique bandwidth allocation then the behavior is `UNSPECIFIED`.

The `useShared` and `sharedAT` fields are reserved if the bandwidth controller
does not support bandwidth allocation per access-type.

[NOTE]
====
When unique bandwidth allocation for an access-type is not required then one or
more access-types may be configured with a shared bandwidth allocation. For
example, consider a bandwidth controller that supports 3 access-types. The
access-type 0 and 1 of `RCID` 3 are configured with unique bandwidth allocations
and the access-type 2 is configured to share bandwidth allocation with
access-type 1. The example configuration is illustrated as follows:

[width=100%]
[%header, cols="4,^1,^1,^1,^1"]
|===
|                  |  `Rbwb`  |  `Mweight`  |  `useShared`  |  `sharedAT`
| `RCID=3`, `AT=0` | `100`    |    `16`     |      `0`      |     `N/A`
| `RCID=3`, `AT=1` | `50`     |    `16`     |      `0`      |     `N/A`
| `RCID=3`, `AT=2` | `N/A`    |    `N/A`    |      `1`      |      `1`
|===

====
