[[QOS_SW_GUIDE]]
== Software Guidelines

=== Reporting capacity and bandwidth controllers

The capability and bandwidth controllers that are present in the system should
be reported to operating systems using methods such as ACPI and/or device tree.
For each capacity and bandwidth controller, the following information should be
reported using these methods:

* Type of controller (e.g, cache, interconnect, memory, etc.)
* Location of the register programming interface for the controller
* Placement and topology describing the hart and IO bridges that share the
  resources controlled by the controller
* The number of QoS identifiers supported by the controller

=== Context switching QoS Identifiers

Typically, the contents of the `sqoscfg` CSR are updated with a new `RCID`
and/or `MCID` by the HS/S-mode scheduler if the `RCID` and/or `MCID` of the
new workload (a process or a VM) is not same as that of the old workload.

A context switch usually involves saving the context associated with the
workload being switched away from and restoring the context of the workload
being switched to. Such context switch may be invoked in response to an explicit
call from the workload (i.e, as a function of an `ECALL` invocation) or may be
done asynchronously (e.g., in response to a timer interrupt). In such cases the
scheduler may want to execute with the `sqoscfg` configuration of the
workload being switched away from such that this execution is attributed to the
workload being switched away from and then prior to restoring the new workloads
context, first switch to the `sqoscfg` configuration appropriate for the
workload being switched to such that all of that execution is attributed to
the new workload. Further in this context switch process, if the scheduler
intends some of its execution to be attributed to neither the outgoing
workload nor the incoming workload, then the scheduler may switch to a new
`sqoscfg` configuration that is different from that of either of the workloads
for the duration of such execution.

=== QoS configurations for virtual machines

Usually for virtual machines the resource allocations are configured by the
hypervisor. Usually the Guest OS in a virtual machine does not participate in
the QoS flows as the Guest OS does not know the physical capabilities of the
platform or the resource allocations for other virtual machines in the system.

If a use case requires it, a hypervisor may virtualize the QoS capability to a
VM by virtualizing the memory-mapped CBQRI register interface and virtualizing
the virtual-instruction exception on access to `sqoscfg` CSR by the Guest OS.

[NOTE]
====
If the use of directly selecting among a set of `RCID` and/or `MCID` by a VM
becomes more prevalent and the overhead of virtualizing the `sqoscfg` CSR using
the virtual instruction exception is not acceptable then a future extension may
be introduced where the `RCID`/`MCID` attempted to be written by VS mode are
used as a selector for a set of `RCID`/`MCID` that the hypervisor configures in
a set of HS mode CSRs.
====

=== QoS Identifiers for supervisor and machine mode

The `RCID` and `MCID` configured in `sqoscfg` also apply to execution in
S/HS-mode but is typically not an issue. Usually, S/HS-mode execution occurs to
provide services, such as through the SBI, to software executing at lower
privilege. Since the S/HS-mode invocation was to provide a service for the
lower privilege mode, the S/HS-mode software may not modify the `sqoscfg` CSR.

The `RCID` and `MCID` configured in `sqoscfg` also apply to execution in M-mode
but is typically not an issue. Usually, M-mode execution occurs to provide
services, such as through the SBI interface, to software executing at lower
privilege. Since the M-mode invocation was to provide a service for the lower
privilege mode, the M-mode software may not modify the `sqoscfg` CSR.

If a use case requires use of separate `RCID` and/or `MCID` for software
execution in S/HS-mode or in M-mode, then the M/S/HS-mode SW may update the
`sqoscfg` CSR and restore it prior to returning to the lower privilege mode
execution. QoS capabilities are statistical in nature and the small duration,
such as the few instructions in the M/S/HW-mode trap handler entrypoint, for
which the trap handler may execute with the `RCID`/ `MCID` established for lower
privilege mode operation may not be statistically significant.
