[[QOS_HW_GUIDE]]
== Hardware Guidelines

[[QOS_SIZING]]
=== Sizing QoS Identifiers

In a typical implementation the number of `RCID` bits implemented (e.g., to
support 10s of `RCIDs`) may be smaller than the number of `MCID` bits
implemented (e.g., to support 100s of `MCIDs`). 

It is a typical usage to associate a group of applications/VMs with a common
`RCID` and thus sharing a common pool of resource allocations. The resource
allocations for the `RCID` is established to meet the SLA objectives of all
members of the group. If SLA objectives of one or more members of the group
stop being met, the resource usage of one or more members of the group may be
monitored by associating them with a unique `MCID` and this iterative analysis
process used to determine the optimal strategy - increasing resources allocated
to the `RCID`, moving some members to a different `RCID`, migrating some members
away to another machine, etc. - for restoring the SLA. Having a sufficiently
large pool of `MCID` speeds up this analysis.

[NOTE]
====
To achieve maximum flexibility in the allocation of QoS IDs to workloads, it is
recommended that all resource controllers in the system support an identical
number of `RCID` and `MCID`. Requests typically need to be processed by multiple
controllers, such as caches, fabrics, and memory controllers. In such cases, if
not all controllers accessed by a request support an identical number of IDs,
software will be constrained, using only the IDs supported by all controllers.
====


=== Sizing monitoring counters

Typically software samples the monitoring counters periodically to monitor
capacity and bandwidth usage. The width of the monitoring counters is
recommended to be wide enough to not cause more than one overflow per sample
when sampled at a frequency of 1 Hz.

