[[QOS_ID]]
== QoS Identifiers 

Monitoring or allocation of resources requires a way to identify the originator
of the request to access the resource.

The CBQRI extension provides a mechanism by which a workload can be associated
with a resource control ID (`RCID`) and a monitoring counter ID (`MCID`) that
accompany each request made by the workload to shared resources.

To provide differentiated services to workloads, the CBQRI extension defines
a mechanism to configure resource usage limits, in the form of capacity or
bandwidth, and optionally a priority for an `RCID` in the resource controllers
that control accesses to such shared resources.

To monitor the resource utilization by a workload  the CBQRI extension defines
a mechanism to configure counters identified by the `MCID` to count events in
the resource controllers that control accesses to such shared resources.

=== Associating `RCID` and `MCID` with requests

==== RISC-V hart initiated requests

The `sqoscfg` CSR is a 32-bit S/HS-mode read/write register to configure a
resource control ID (`RCID`) and a monitoring counter ID (`MCID`). The `RCID`
and `MCID` accompany each request made by the hart to shared resources such
as interconnects, caches, memory, etc.

.`sqoscfg` register for RV32 and RV64

[wavedrom, , ]
....
{reg: [
  {bits: 12, name: 'RCID (WARL)'},
  {bits:  4, name: 'WPRI'},
  {bits: 12, name: 'MCID (WARL)'},
  {bits:  4, name: 'WPRI'},
], config:{lanes: 1, hspace:1024}}
....

[NOTE]
====
The type of request made to the shared resource controller depends on the type
of shared resource. In case of resources such as caches or memory these may be
a memory access request. In case of resources such as CPU dispatch slots and
retirement bandwidth the request may be to allocate such resources for
execution.
====

The `RCID` in the request is used by the resource controllers to determine the
resource allocations (e.g., cache occupancy limits, memory bandwidth limits,
etc.) to enforce. The `MCID` in the request is used by the resource controllers
to identify the ID of a counter to monitor resource usage (e.g., cache
occupancy, memory bandwidth, etc.).

Access to `sqoscfg` when `V=1` causes a virtual-instruction exception.

[NOTE]
====
At reset it is suggested that the `RCID` field of `sqoscfg` be set to 0 as
typically the resource controllers in the SoC default to a reset behavior
of associating all capacity or bandwidth to the `RCID` value of 0.

The value of `MCID` at reset, unlike the `RCID`, does not affect functional
behavior. Implementations may choose a convenient legal value for the `MCID`
reset value.
====

The `RCID` and `MCID` configured in the `sqoscfg` CSR apply to all privilege
modes of software execution on that hart.

The `QOSE` (bit 58) field of `menvcfg` (and `menvcfgh`) controls if the
`sqoscfg` CSR is accessible in modes less privileged than M. When `QOSE` is 0,
attempts to access `sqoscfg` CSR at privilege modes less privileged than M cause
an illegal instruction exception.

==== Device initiated requests

Devices may be configured with an `RCID` and `MCID` for requests originated 
from the device if the device implementation supports such capability. The 
method to configure the QoS identifiers into devices is `UNSPECIFIED`.

Where the device does not natively support being configured with an `RCID`
and `MCID`, the implementation may provide a shim at the device interface that
may be configured with the `RCID` and `MCID` that are associated with requests
originating from the device. The method to configure such QoS identifiers into
a shim is `UNSPECIFIED`.

If the system supports an IOMMU, then the IOMMU may be configured with the
`RCID` and `MCID` to associate requests from the device with the QoS
identifiers. The RISC-V IOMMU specification may support a future standard
extension to support this configuration.

=== Access-type (`AT`)

In some usages, in addition to providing differentiated service among workloads,
the ability to differentiate between resource usage for accesses made by the
same workload may be required. For example, the capacity allocated in a shared
cache for code storage may be differentiated from the capacity allocated for
data storage and thereby avoid code from being evicted from such shared cache
due to a data access.

When differentiation based on access type (e.g. code vs. data) is supported the
requests also carry an access-type (`AT`) indicator. The resource controllers
may be configured with separate capacity and/or bandwidth allocations for each
supported access-type. The CBQRI extension defines a 3-bit `AT` field, encoded
as specified in <<AT_ENC>>, in the register interface to configure
differentiated resource allocation and monitoring for each `AT`.

[[AT_ENC]]
.Encodings of `AT` field
[width=75%]
[%header, cols="5,5,20"]
|===
|Value | Name     | Description
| 0    | `Data`   | Requests to access data.
| 1    | `Code`   | Requests for code execution.
| 2-5  | Reserved | Reserved for future standard use.
| 6-7  | Custom   | Designated for custom use.
|===

If a request is received with an unsupported `AT` value then the resource
controller behaves as if the `AT` value was 0.
