[[QOS_SW_GUIDE]]
== Software Guidelines

=== Context switching QoS Identifiers

Typically, the contents of the `sqoscfg` CSR is updated with a new `RCID`
and/or `MCID` by the HS/S-mode scheduler if the `RCID` and/or `MCID` of the
new process/VM is not same as that of the old process/VM.

Usually for virtual machines the resource allocations are configured by the
hypervisor. Usually the Guest OS in a virtual machine does not participate in
the QoS flows as the Guest OS does not know the physical capabilities of the
platform or the resource allocations for other virtual machines in the system.
If a use case requires it, a hypervisor may virtualize the QoS capability to a
VM by virtualizing the memory-mapped CBQRI register interface and using the
virtual-instruction exception on access to `sqoscfg` CSR.

[NOTE]
====
If the use of directly selecting among a set of `RCID` and/or `MCID` by a VM
becomes more prevalent and the overhead of virtualizing the `sqoscfg` CSR using
the virtual instruction exception is not acceptable then a future extension may
be introduced where the `RCID`/`MCID` attempted to be written by VS mode are
used as a selector for a set of `RCID`/`MCID` that the hypervisor configures in
a set of HS mode CSRs.
====

A Hypervisor may cause a context switch from one virtual machine to another. The
context switch usually involves saving the context associated with the VM being
switched away from and restoring the context of the VM being switched to. Such
context switch may be invoked in response to an explicit call from the VM (i.e,
as a function of an `ECALL` invocation) or may be done asynchronously (e.g., in
response to a timer interrupt). In such cases the hypervisor may want to execute
with the `sqoscfg` configurations of the VM being switched away from such that
the execution is attributed to the VM being switched from and then prior to
executing the context switch code associated with restoring the new VMs context
first switch to the `sqoscfg` appropriate for the new VM being switched to such
that all of that execution is attributed to the new VM. Further in this context
switch process, if the hypervisor intends some of the execution to be attributed
to neither the outgoing VM nor the incoming VM, then the hypervisor may switch
to a new configuration that is different from the configuration of either of the
VMs for the duration of such execution. QoS extensions are statistical in
nature and the small duration, such as the few instructions in the hypervisor
trap handler entrypoint, for which the HS-mode may execute with the `RCID`/
`MCID` established for lower privilege mode operation may not be statistically
significant.

=== QoS Identifiers for supervisor and machine mode

The `RCID` and `MCID` configured in `sqoscfg` also apply to execution in
S/HS-mode but is typically not an issue. Usually, S/HS-mode execution occurs to
provide services, such as through the SBI, to software executing at lower
privilege. Since the S/HS-mode invocation was to provide a service for the
lower privilege mode, the S/HS-mode software may not modify the `sqoscfg` CSR.

If a use case requires use of separate `RCID` and/or `MCID` for software
execution in S/HS-mode, then the S/HS-mode SW may update the `sqoscfg` CSR and
restore it prior to returning to the lower privilege mode execution.

The `RCID` and `MCID` configured in `sqoscfg` also apply to execution in M-mode
but is typically not an issue. Usually, M-mode execution occurs to provide
services, such as through the SBI interface, to software executing at lower
privilege. Since the M-mode invocation was to provide a service for the lower
privilege mode, the M-mode software may not modify the `sqoscfg` CSR. If a use
case requires use of a separate `RCID` and/or `MCID` for software execution in
M-mode, then the M-mode SW may update the `sqoscfg` CSR and restore it prior to
returning to lower privilege mode execution.

=== Secure register programming interface

Security monitors such as the TEE security monitor must protect the secure
register programming interface from read or write access by non-secure entities.
Methods such as PMPs, page tables, etc. may be employed to implementation such
protection mechanisms.

When multiple security domains exists the control of the secure register
programming interface must be retained by the security monitor that is in the
trust boundary of the security domains controlled by that monitor.

When multiple security domains exists, the security manager of the security
domains must not in general provide QoS information about one security domain to
another or allow one security domain to affect the QoS configurations of another
security domain; unless an explicit security policy defined by the security
domain manager allows such sharing.

