= RISC-V Capacity and Bandwidth Controller QoS Register Interface

This document is capturing discussions at the CMQRI TG and attempts to document the baseline.
This is not official specification and everything in this document may change. 

Quality of Service (QoS) is the minimal end-to-end performance that is guaranteed in advance
by a service level agreement (SLA) to an application.

System software needs additional tools to control interference to an application and thereby
reduce the variability in performance experienced by one application due to other application's
cache capacity usage, memory bandwidth usage, interconnect bandwidth usage, power usage, etc.
through a capacity and bandwidth allocation extension.

Effective use of the capacity and bandwidth allocation extension requires hardware to provide a
capacity and bandwidth monitoring extension by which the resource requirements of an application
needed to meet a certain performance goal can be characterized.

= License

This work is licensed under a Creative Commons Attribution 4.0 International License (CC-BY-4.0).
See the link:LICENSE[LICENSE] file for details.

= Contributors

Contributors to this specification are contained in the link:contributors.adoc[contributors] file.

For instructions on how to contribute please see the link:CONTRIBUTING.md[CONTRIBUTING] file.

= Dependencies

This project is built using AsciiDoctor (Ruby). The repository has been setup to build the PDF on
checkin using GitHub actions.  Workflow dependencies are located in the `dependencies` directory.

For more information on AsciiDoctor, specification guidelines, or building locally, see the
https://github.com/riscv/docs-dev-guide[RISC-V Documentation Developer Guide].

= Cloning the project

This project uses https://git-scm.com/book/en/v2/Git-Tools-Submodules[GitHub Submodules]
to include the https://github.com/riscv/docs-resources[RISC-V docs-resources project]
to achieve a common look and feel.

When cloning this repository for the first time, you must either use
`git clone --recurse-submodules` or execute `git submodule init` and `git submodule update` after the clone to populate the docs-resources directory.  Failure to clone the submodule, will result
in the PDF build fail with an error message like the following:

    $ make
    asciidoctor-pdf \
    -a toc \
    -a compress \
    -a pdf-style=docs-resources/themes/riscv-pdf.yml \
    -a pdf-fontsdir=docs-resources/fonts \
    --failure-level=ERROR \
    -o profiles.pdf profiles.adoc
    asciidoctor: ERROR: could not locate or load the built-in pdf theme `docs-resources/themes/riscv-pdf.yml'; reverting to default theme
    No such file or directory - notoserif-regular-subset.ttf not found in docs-resources/fonts
      Use --trace for backtrace
    make: *** [Makefile:7: profiles.pdf] Error 1

= Building the document

The final specification form of PDF can be generated using the `make` command.
