= RISC-V Capacity and Bandwidth Controller QoS Register Interface

This document is capturing discussions at the CMQRI TG and attempts to document the baseline.
This is not official specification and everything in this document may change. 

Quality of Service (QoS) is the minimal end-to-end performance that is guaranteed in advance
by a service level agreement (SLA) to an application.

System software needs additional tools to control interference to an application and thereby
reduce the variability in performance experienced by one application due to other application's
cache capacity usage, memory bandwidth usage, interconnect bandwidth usage, power usage, etc.
through a capacity and bandwidth allocation capability.

Effective use of the capacity and bandwidth allocation capability requires hardware to provide a
capacity and bandwidth monitoring capability by which the resource requirements of an application
needed to meet a certain performance goal can be characterized.

= License

This work is licensed under a Creative Commons Attribution 4.0 International License (CC-BY-4.0).
See the link:LICENSE[LICENSE] file for details.

= Contributors

Contributors to this specification are contained in the link:contributors.adoc[contributors] file.

For instructions on how to contribute please see the link:CONTRIBUTING.md[CONTRIBUTING] file.

= Dependencies

To build the document, you'll need the following tools installed on your system:

```
  Make
  asciiDoctor-pdf, asciidoctor-bibtex, asciidoctor-diagram and asciidoctor-mathematical
  Docker
```

= Cloning and Building the Document

This project uses submodules to include the RISC-V documentation toolchain. 

```
  git clone --recurse-submodule https://github.com/riscv/riscv-svadu.git
  cd ./riscv-zacas.git
  make VERSION=v1.0.0 REVMARK=Draft
```

`VERSION`: Represents the version of the specification being built. By default, this is set to 'v0.0.0'. You can change this to a different value, like 'v1.0.0', 'v1.1.0', etc., based on the current version of your specification.

`REVMARK`: This represents a revision marker for the project. Its default value is 'Draft'. You may want to change this to something like 'Release', 'Stable' or 'Ratified'.
